language: ruby
rvm:
  - 2.3.3
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS fpl_17_test;'
before_script: "bundle exec rails db:drop db:create db:migrate"
notifications:
  email: false
