# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e54ab89cb830993e4d6b566fad4e00dd299e16b5fd2a5b5338612c8ae23b54e713a75824fbedb39df9f4d45737407d854daba73289c717b9ddeee93fff25f27

test:
  secret_key_base: f6397b52cbec06ccd346c60fd8137da94ba64312efbc3582f09303e9391eba6f201b8e3100fc9dda6b5ab465a64d4f79a935f2e54e4286d345e7fb93883af3b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
